name: Report a bug
description: Report a bug.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please make sure this bug hasn't already been reported by looking through other open/closed issues.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the bug you encountered, e.g. what you were trying to do and what happened instead.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduce
      description: Steps to reproduce the behavior you experienced, including system/browser used and version.
      placeholder: |
        0. Use version X of Y software.
        1. Go to...
        2. Click on...
        3. Scroll down to...
        4. See error!
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Extra
      description: Provide additional information such as logs and/or screenshots of the scenarios in which the bug occurs.
