name: Ask a question
description: Ask a question.
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: Please make sure this question hasn't already been asked by looking through other open/closed issues.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: State your question.
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Extra
      description: Provide additional information such as code snippets or files that provide context for your question.
